language: node_js

repo_token: MqyCLJqYSq6z5PEi10j3bUopYjitkfTe8 # 从coveralls.io获取

node_js:  
     - 6
     - 7
     - 8
script: make test

after_script: npm run cov

after_success:
  "curl -L -l https://coveralls.io/repos/github/navyxie/phone-service/badge.svg?branch=master"